name: rook
summary:  Storage Orchestration for Kubernetes.
description:| an open source cloud-native storage orchestrator for Kubernetes, providing the platform, framework, and support for a diverse set of storage solutions to natively integrate with cloud-native environments.
  
adopt-info: rook

grade: stable
confinement: classic

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  rook:
    command: bin/rook
    plugs:
      - home
      - network
      - docker
      - removable-media

parts:
  rook:
  plugin: nil 
    source: https://github.com/rook/rook.git
    source-type: git
    override-pull: |
      git clone https://github.com/rook/rook.git src/github.com/rook/rook
       cd src/github.com/rook/rook
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      override-build: |
      export GOPATH=$PWD
      cd src/github.com/rook/rook
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/rook/rook/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/rook/rook/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/rook
    build-snaps:
      - go
    build-packages:
      - git
      - sed
